### ISSUE TITLE
Error while building on Windows

### ISSUE THREAD

**Issue by GilmarCorreia** [PickNikRobotics/RSL#103]
Hello! I'm facing a really annoying issue trying to use this package on Windows, and I'm trying to figure out what is happening. I'm trying to do that because this package is the base of the controller_manager, realtime_tools, and generate_parameter_library packages.

First, I'm using:

- OS: Windows 10
- ROS Version: Humble

I'm getting this error when running `colcon build --packages-select rsl`:

```bash
C:\Users\USER\Desktop\ros2_ws\src\RSL\src\random.cpp(37,42): error C2065: 'M_PI': undeclared identifier [C:\Users\USER\Desktop\ros2_ws\build\rsl\rsl.vcxproj]
...
```

So I have modified these files:

- CMakeLists.txt:
```bash
add_library(rsl STATIC
    src/parameter_validators.cpp
    src/random.cpp
)
```

- include/random.hpp:
```cpp
#pragma once
#define _USE_MATH_DEFINES
```

- tests/static_string.cpp:
```cpp
SECTION("Collection constructor") {
    auto const string = "Hello, world!"s;
    auto const static_string = rsl::StaticString<14>(string);
    CHECK(static_string.begin() != static_string.end());
    //auto const * begin = static_string.begin();
    auto begin = static_string.begin();
    CHECK(*begin++ == 'H');
    CHECK(*begin++ == 'e');
    CHECK(*begin++ == 'l');
    CHECK(*begin++ == 'l');
    CHECK(*begin++ == 'o');
    CHECK(*begin++ == ',');
    CHECK(*begin++ == ' ');
    CHECK(*begin++ == 'w');
    CHECK(*begin++ == 'o');
    CHECK(*begin++ == 'r');
    CHECK(*begin++ == 'l');
    CHECK(*begin++ == 'd');
}
```

- tests/try.cpp:
```cpp
static ExpectedType check_try_macro(ExpectedType const& expected) {
    ExpectedType::value_type value = 0; //= TRY(expected);
    return ++value;
}
```

- queue.cpp:
```cpp
SECTION("Concurrently") {
    auto queue = rsl::Queue<int>();

    constexpr auto thread_count = size_t(10);
    constexpr auto item_count = size_t(100);

    auto producers = std::array<std::thread, thread_count>();
    for (auto& producer : producers) {
        //producer = std::thread([&queue] {
        producer = std::thread([&item_count,&queue] {
            for (size_t i = 0; i < item_count; ++i) queue.push(int(i));
        });
    }

    auto items_removed = std::atomic<size_t>(0);
    auto consumers = std::array<std::thread, thread_count>();
    for (auto& consumer : consumers) {
        //consumer = std::thread([&queue, &items_removed] {
        consumer = std::thread([&item_count,&queue, &items_removed] {
            for (size_t i = 0; i < item_count; ++i)
                if (queue.pop(1ms).has_value()) ++items_removed;
        });
    }

    for (auto& producer : producers) producer.join();
    for (auto& consumer : consumers) consumer.join();

    CHECK(queue.size() == thread_count * item_count - items_removed);
}
```

After changing these files, I could compile using `colcon build`, but I got an error from test-rsl.exe:
```bash
CMake Error at C:/Users/USER/Desktop/ros2_ws/build/rsl/_deps/catch2-src/extras/CatchAddTests.cmake:70 (message):
    Error running test executable
    'C:/Users/USER/Desktop/ros2_ws/build/rsl/tests/Release/test-rsl.exe':
  
      Result: Exit code 0xc0000135
  
    
  
      Output: 
  
  Call Stack (most recent call first):
    C:/Users/USER/Desktop/ros2_ws/build/rsl/_deps/catch2-src/extras/CatchAddTests.cmake:175 (catch_discover_tests_impl)
```

How do I remove all tests to build this package? Or how could we solve this issue to compile on Windows?

Thanks!

**Comment by ChrisThrasher** [comment]
`M_PI` is not standard C++. That's our bad. Here's a PR that removes use of that particular compiler extension.

https://github.com/PickNikRobotics/RSL/pull/104

**Comment by ChrisThrasher** [comment]
> After changing these files, I could compile using colcon build, but I got an error from test-rsl.exe:

You can disable the tests by disabling the `BUILD_TESTING` CMake option. No need to build those when you're not developing the library.

**Comment by ChrisThrasher** [comment]
https://github.com/PickNikRobotics/RSL/pull/105

The tests ought to have been disabled by default so I'm fixing that as well so that nobody has to manually disable them.

**Comment by ChrisThrasher** [comment]
Try rebuilding with the latest `main` branch and let me know if any of these issues persist. Thanks for the report!

**Comment by GilmarCorreia** [comment]
Thank you for your prompt response. I am currently encountering the following error using the main branch:

OS: Windows 10
ROS Version: Humble
Microsoft Visual Studio 2019

```bash
--- stderr: rsl
Traceback (most recent call last):
  File "c:\python38\lib\site-packages\colcon_core\executor\__init__.py", line 91, in __call__
    rc = await self.task(*args, **kwargs)
  File "c:\python38\lib\site-packages\colcon_core\task\__init__.py", line 93, in __call__
    return await task_method(*args, **kwargs)
  File "c:\python38\lib\site-packages\colcon_ros\task\catkin\build.py", line 74, in build
    rc = await extension.build(
  File "c:\python38\lib\site-packages\colcon_cmake\task\cmake\build.py", line 103, in build
    rc = await self._build(
  File "c:\python38\lib\site-packages\colcon_cmake\task\cmake\build.py", line 236, in _build
    if not await has_target(args.build_base, target):
  File "c:\python38\lib\site-packages\colcon_cmake\task\cmake\__init__.py", line 61, in has_target
    assert target == 'install'
AssertionError
```

**Comment by ChrisThrasher** [comment]
I can't make sense of that error, sorry. My hunch is that the error is related to how you're using colcon but I'm not sure.

**Comment by GilmarCorreia** [comment]
I have resolved the issue using the following command:
```bash
colcon build --packages-select rsl --merge-install --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -G Ninja
```
Thank you.

**Comment by MIXISAMA** [comment]
Here is another solution with `--catkin-skip-building-tests`.

```ps1
colcon build --packages-select rsl --merge-install --catkin-skip-building-tests
```

This is due to this [code](https://github.com/colcon/colcon-ros/blob/a0d62231efeb0e89a32bffa17ee3bab44dc485a3/colcon_ros/task/catkin/build.py#L66-L75), adding `tests` in `additional_targets`.

```py
        # invoke the build
        additional_targets = []
        # if no specific target is specified consider building the 'tests'
        # target and continue if such a target doesn't exist
        if args.cmake_target is None:
            if not args.catkin_skip_building_tests:
                additional_targets.append('tests')
                args.cmake_target_skip_unavailable = True
        rc = await extension.build(
            skip_hook_creation=True, additional_targets=additional_targets)
```
